"""a

Revision ID: 51444db418ba
Revises: e10e26f8c504
Create Date: 2019-11-15 14:54:33.406990

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '51444db418ba'
down_revision = 'e10e26f8c504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('microwave', sa.Column('datetime', sa.String(length=220), nullable=True))
    op.add_column('microwave', sa.Column('station_id', sa.String(length=20), nullable=True))
    op.drop_column('microwave', 'datetime1')
    op.drop_column('microwave', 'station_id1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('microwave', sa.Column('station_id1', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('microwave', sa.Column('datetime1', mysql.VARCHAR(length=220), nullable=True))
    op.drop_column('microwave', 'station_id')
    op.drop_column('microwave', 'datetime')
    # ### end Alembic commands ###
