"""add note timestamp22

Revision ID: 7eee5ebcfe06
Revises: 51444db418ba
Create Date: 2019-11-15 14:57:37.457928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eee5ebcfe06'
down_revision = '51444db418ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('microwave', sa.Column('datetype', sa.String(length=2), nullable=True))
    op.add_column('microwave', sa.Column('temp', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('microwave', 'temp')
    op.drop_column('microwave', 'datetype')
    # ### end Alembic commands ###
