"""add note timestamp

Revision ID: c895b1133509
Revises: 
Create Date: 2019-11-15 14:41:44.661406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c895b1133509'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('microwave',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('station_id', sa.String(length=20), nullable=True),
    sa.Column('datetime', sa.DATETIME(timezone=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('microwave')
    # ### end Alembic commands ###
