"""add note timestamp12

Revision ID: e10e26f8c504
Revises: c895b1133509
Create Date: 2019-11-15 14:51:45.326156

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e10e26f8c504'
down_revision = 'c895b1133509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('microwave', sa.Column('datetime1', sa.String(length=220), nullable=True))
    op.add_column('microwave', sa.Column('station_id1', sa.String(length=20), nullable=True))
    op.drop_column('microwave', 'station_id')
    op.drop_column('microwave', 'datetime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('microwave', sa.Column('datetime', mysql.DATETIME(), nullable=True))
    op.add_column('microwave', sa.Column('station_id', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('microwave', 'station_id1')
    op.drop_column('microwave', 'datetime1')
    # ### end Alembic commands ###
